Implement register & history
0-Auth/0Auth_extension pull request #31
Opened 2020-11-10 09:04 UTC by HyeockJinKim

Closes #29

2020-11-10 14:56 UTC, HyeockJinKim reviewed
self review

2020-11-10 14:56 UTC, HyeockJinKim commented on background/contentScript.js
> +      }
Code for compatibility with the previous version of the 0auth library.

2020-11-10 14:56 UTC, HyeockJinKim commented on background/contentScript.js
> +chrome.runtime.onMessage.addListener((request, _sender, _sendResponse) => {
unused parameter.

2020-11-10 14:56 UTC, HyeockJinKim commented on manifest.json
> +  "permissions": ["activeTab", "declarativeContent", "storage", "unlimitedStorage"],
Permission to remove the storage capacity limit stored in the extension.

2020-11-10 19:17 UTC, anthonyminyungi requested changes
I reviewed all of the code you uploaded, I think you have to check your formatting environment.

2020-11-10 19:17 UTC, anthonyminyungi commented on src/components/page/public/index.tsx
> +import {Property, Signature} from "@0auth/message";
I set the ESLint definitely, why didn't it applied here?

2020-11-10 19:17 UTC, anthonyminyungi commented on src/components/page/public/index.tsx
> +  //         break;
Could you explain what is this code block of comments?

2020-11-11 14:57 UTC, anthonyminyungi approved these changes
LGTM.

2020-11-11 15:00 UTC, merged